import { useState } from 'react';
import { CheckCircle2, Eye, MessageSquare, Pencil, Phone, Trash2, UserRound, Users } from 'lucide-react';

const sellers = [
  { id: 'SEL-001', name: 'মোঃ রফিকুল ইসলাম', phone: '+8801711000001', email: 'rafiqul@example.com', nid: 'ভেরিফাইড', listings: '২ active · ১ sold', type: 'Individual Owner', joined: '০১ সেপ্টেম্বর ২০২৬' },
  { id: 'SEL-002', name: 'রিভারভিউ বিল্ডার্স লিঃ', phone: '+8801811000002', email: 'info@riverview.example', nid: 'ভেরিফাইড', listings: '১ active', type: 'Developer', joined: '০৫ সেপ্টেম্বর ২০২৬' },
  { id: 'SEL-003', name: 'বরিশাল হোম বিল্ডার্স', phone: '+8801911000003', email: 'hello@barishalhome.example', nid: 'Pending', listings: '১ active', type: 'Real Estate Agent', joined: '১১ সেপ্টেম্বর ২০২৬' }
];
const leads = [
  { id: 'LEAD-001', name: 'সাব্বির আহমেদ', phone: '+8801611000011', property: 'LF-BRL-001', budget: '৳ ৪৫-৫৫ লাখ', area: 'আমতলা', status: 'New', note: 'আজ কল করে বাজেট নিশ্চিত করতে হবে' },
  { id: 'LEAD-002', name: 'তানজিলা রহমান', phone: '+8801611000012', property: 'LF-BRF-002', budget: '৳ ৬০-৭০ লাখ', area: 'বগুড়া রোড', status: 'Site Visit Scheduled', note: 'আগামীকাল বিকেল ৪টায় site visit' },
  { id: 'LEAD-003', name: 'মোঃ নাঈম', phone: '+8801611000013', property: 'LF-BRL-003', budget: '৳ ৮০-৯৫ লাখ', area: 'সিএন্ডবি রোড', status: 'Contacted', note: 'ডকুমেন্টের ছবি পাঠানো হয়েছে' }
];
const statuses = ['Published', 'Pending', 'Sold'];
const transactions = [
  { id: 'TXN-2026-001', property: 'LF-BRL-001', type: 'Income', category: 'ব্রোকারেজ কমিশন', amount: 125000, method: 'ব্যাংক ট্রান্সফার', status: 'Paid', date: '১৪ সেপ্টেম্বর ২০২৬' },
  { id: 'TXN-2026-002', property: 'LF-BRF-002', type: 'Income', category: 'ভেরিফিকেশন ফি', amount: 15000, method: 'বিকাশ', status: 'Paid', date: '১২ সেপ্টেম্বর ২০২৬' },
  { id: 'TXN-2026-003', property: 'LF-BRL-003', type: 'Income', category: 'Featured listing ফি', amount: 10000, method: 'ক্যাশ', status: 'Pending', date: '১০ সেপ্টেম্বর ২০২৬' },
  { id: 'TXN-2026-004', property: '-', type: 'Expense', category: 'টিম ও স্টাফ খরচ', amount: 18000, method: 'ক্যাশ', status: 'Paid', date: '০৮ সেপ্টেম্বর ২০২৬' },
  { id: 'TXN-2026-005', property: '-', type: 'Expense', category: 'মার্কেটিং ও বিজ্ঞাপন', amount: 12000, method: 'ব্যাংক ট্রান্সফার', status: 'Paid', date: '০৫ সেপ্টেম্বর ২০২৬' },
  { id: 'TXN-2026-006', property: '-', type: 'Expense', category: 'অফিস পরিচালনা', amount: 25000, method: 'ব্যাংক ট্রান্সফার', status: 'Due', date: '০১ সেপ্টেম্বর ২০২৬' }
];

export default function AdminCRM({ properties, isLoggedIn, setIsLoggedIn, pin, setPin }) {
  const [tab, setTab] = useState('inventory');
  const [inventory, setInventory] = useState(properties);
  if (!isLoggedIn) return <div className="max-w-md mx-auto my-12 p-6 bg-white border rounded-xl text-center"><h2 className="font-bold text-lg mb-4">এডমিন প্যানেল প্রবেশ করুন</h2><form onSubmit={(event) => { event.preventDefault(); if (pin === '1234') setIsLoggedIn(true); else alert('ভুল পিন (পাসওয়ার্ড: 1234)'); }}><input type="password" placeholder="PIN দিন (ডিফোল্ট: 1234)" value={pin} onChange={(event) => setPin(event.target.value)} className="w-full text-xs p-2.5 border rounded-lg mb-3" /><button type="submit" className="w-full bg-[#00875A] text-white py-2.5 rounded-lg text-xs font-bold">লগইন</button></form></div>;
  const activeCount = inventory.filter((property) => property.status === 'Published').length;
  const soldCount = inventory.filter((property) => property.status === 'Sold').length;
  const changeStatus = (id) => setInventory((current) => current.map((property) => property.id === id ? { ...property, status: statuses[(statuses.indexOf(property.status) + 1) % statuses.length] } : property));
  const deleteProperty = (id) => setInventory((current) => current.filter((property) => property.id !== id));
  return <div className="max-w-7xl mx-auto px-4 py-8"><header className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8"><div><p className="text-xs font-bold uppercase tracking-widest text-[#00875A]">Land&Flat CRM</p><h1 className="text-2xl sm:text-3xl font-extrabold text-gray-900 mt-1">বরিশাল অপারেশন ড্যাশবোর্ড</h1></div><button onClick={() => setIsLoggedIn(false)} className="self-start text-xs bg-red-100 text-red-600 px-3 py-2 rounded-lg font-bold">লগআউট</button></header><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8"><SummaryCard label="মোট প্রপার্টি" value={inventory.length} icon={Users} color="text-blue-600" /><SummaryCard label="সক্রিয় লিস্টিং" value={activeCount} icon={CheckCircle2} color="text-[#00875A]" /><SummaryCard label="নতুন ইনকোয়ারি" value={leads.filter((lead) => lead.status === 'New').length} icon={MessageSquare} color="text-amber-600" /><SummaryCard label="বিক্রীত প্রপার্টি" value={soldCount} icon={CheckCircle2} color="text-violet-600" /></div><nav className="flex gap-2 border-b border-gray-200 mb-6 overflow-x-auto"><TabButton active={tab === 'inventory'} onClick={() => setTab('inventory')}>ইনভেন্টরি</TabButton><TabButton active={tab === 'sellers'} onClick={() => setTab('sellers')}>সেলার মনিটরিং</TabButton><TabButton active={tab === 'leads'} onClick={() => setTab('leads')}>বায়ার ও লিড</TabButton><TabButton active={tab === 'finance'} onClick={() => setTab('finance')}>অ্যাকাউন্টস / ফাইন্যান্স</TabButton></nav>{tab === 'inventory' && <InventoryTable inventory={inventory} changeStatus={changeStatus} deleteProperty={deleteProperty} />}{tab === 'sellers' && <SellerTable />}{tab === 'leads' && <LeadTable />}{tab === 'finance' && <FinanceTable />}</div>;
}

function SummaryCard({ label, value, icon: Icon, color }) { return <div className="bg-white rounded-xl p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs text-gray-500">{label}</span><Icon className={`w-5 h-5 ${color}`} /></div><strong className="block mt-2 text-2xl font-extrabold text-gray-900">{value}</strong></div>; }
function TabButton({ active, onClick, children }) { return <button onClick={onClick} className={`shrink-0 px-4 py-3 text-sm font-bold border-b-2 ${active ? 'border-[#00875A] text-[#00875A]' : 'border-transparent text-gray-500'}`}>{children}</button>; }
function InventoryTable({ inventory, changeStatus, deleteProperty }) { return <section><div className="flex justify-between mb-4"><div><h2 className="text-xl font-bold text-gray-900">প্রপার্টি ইনভেন্টরি</h2><p className="text-xs text-gray-500 mt-1">সেলার, লিড এবং listing performance</p></div><span className="text-xs text-gray-500">{inventory.length} টি listing</span></div><div className="bg-white rounded-xl shadow-sm overflow-x-auto"><table className="w-full min-w-[1050px] text-xs text-left"><thead className="bg-slate-50 text-gray-500"><tr>{['প্রপার্টি','সেলার','লোকেশন','লিড','ভিউ','স্ট্যাটাস','অ্যাকশন'].map((heading) => <th key={heading} className="p-4">{heading}</th>)}</tr></thead><tbody>{inventory.map((property, index) => <tr key={property.id} className="border-t border-gray-100 align-top"><td className="p-4"><strong className="block max-w-xs text-gray-900">{property.title}</strong><span className="text-[10px] text-gray-400">{property.propertyId} · {property.formattedPrice}</span></td><td className="p-4"><span className="block font-semibold text-gray-800">{sellers[index % sellers.length].name}</span><a href={`tel:${sellers[index % sellers.length].phone}`} className="mt-1 flex items-center gap-1 text-[#00875A]"><Phone className="w-3 h-3" /> কল করুন</a></td><td className="p-4 text-gray-600">{property.location}</td><td className="p-4 font-bold">{[12, 8, 5, 4][index % 4]}</td><td className="p-4"><span className="flex items-center gap-1"><Eye className="w-3.5 h-3.5" /> {[146, 98, 74, 61][index % 4]}</span></td><td className="p-4"><button onClick={() => changeStatus(property.id)} className={`rounded-full px-2.5 py-1 font-bold ${property.status === 'Sold' ? 'bg-violet-100 text-violet-700' : property.status === 'Pending' ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-[#00875A]'}`}>{property.status === 'Published' ? 'Active' : property.status}</button></td><td className="p-4"><div className="flex gap-2"><button onClick={() => alert(`Edit: ${property.propertyId}`)} aria-label="সম্পাদনা" className="p-2 rounded-lg bg-blue-50 text-blue-600"><Pencil className="w-3.5 h-3.5" /></button><button onClick={() => deleteProperty(property.id)} aria-label="ডিলিট" className="p-2 rounded-lg bg-red-50 text-red-600"><Trash2 className="w-3.5 h-3.5" /></button></div></td></tr>)}</tbody></table></div></section>; }
function SellerTable() { return <DataTable title="সেলার মনিটরিং" subtitle="বিক্রেতাদের পরিচয়, যোগাযোগ এবং listing performance" headers={['সেলার ID ও নাম','যোগাযোগ','NID status','লিস্টিং সংখ্যা','সেলার টাইপ','যোগদানের তারিখ']} rows={sellers.map((seller) => [<><strong className="block">{seller.name}</strong><small>{seller.id}</small></>, <><a href={`tel:${seller.phone}`} className="text-[#00875A]">{seller.phone}</a><small className="block">{seller.email}</small></>, seller.nid, seller.listings, seller.type, seller.joined])} />; }
function LeadTable() { return <DataTable title="বায়ার ও লিড ম্যানেজমেন্ট" subtitle="নতুন buyer inquiry, budget এবং follow-up status" headers={['বায়ার / লিড','প্রপার্টি ID','বাজেট ও এলাকা','লিড স্ট্যাটাস','ফলো-আপ নোট','অ্যাকশন']} rows={leads.map((lead) => [<><strong className="block">{lead.name}</strong><a href={`tel:${lead.phone}`} className="text-[#00875A]">{lead.phone}</a></>, lead.property, <><strong className="block">{lead.budget}</strong>{lead.area}</>, lead.status, lead.note, <button onClick={() => alert(`Lead: ${lead.id}`)} className="flex items-center gap-1 rounded-lg bg-[#00875A] px-3 py-2 text-white"><UserRound className="w-3.5 h-3.5" /> Follow up</button>])} />; }
function DataTable({ title, subtitle, headers, rows }) { return <section><div className="mb-4"><h2 className="text-xl font-bold text-gray-900">{title}</h2><p className="text-xs text-gray-500 mt-1">{subtitle}</p></div><div className="bg-white rounded-xl shadow-sm overflow-x-auto"><table className="w-full min-w-[1050px] text-xs text-left"><thead className="bg-slate-50 text-gray-500"><tr>{headers.map((header) => <th key={header} className="p-4">{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-gray-100 align-top">{row.map((cell, cellIndex) => <td key={cellIndex} className="p-4 text-gray-700">{cell}</td>)}</tr>)}</tbody></table></div></section>; }

function FinanceTable() {
  const income = transactions.filter((transaction) => transaction.type === 'Income').reduce((total, transaction) => total + transaction.amount, 0);
  const expenses = transactions.filter((transaction) => transaction.type === 'Expense').reduce((total, transaction) => total + transaction.amount, 0);
  const monthlyIncome = transactions.filter((transaction) => transaction.type === 'Income' && transaction.status === 'Paid').reduce((total, transaction) => total + transaction.amount, 0);
  const money = (amount) => `৳ ${amount.toLocaleString('en-IN')}`;
  const statusStyle = (status) => status === 'Paid' ? 'bg-emerald-100 text-[#00875A]' : status === 'Pending' ? 'bg-amber-100 text-amber-700' : 'bg-red-100 text-red-700';

  return <section><div className="mb-4"><h2 className="text-xl font-bold text-gray-900">অ্যাকাউন্টস ও ফাইন্যান্স</h2><p className="text-xs text-gray-500 mt-1">আয়, ব্যয় এবং প্রতিটি transaction-এর বর্তমান অবস্থা</p></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6"><SummaryCard label="মোট আয়" value={money(income)} icon={MessageSquare} color="text-[#00875A]" /><SummaryCard label="চলতি মাসের আয়" value={money(monthlyIncome)} icon={CheckCircle2} color="text-blue-600" /><SummaryCard label="মোট খরচ" value={money(expenses)} icon={Eye} color="text-red-600" /><SummaryCard label="খাঁটি লাভ" value={money(income - expenses)} icon={Users} color="text-violet-600" /></div><div className="bg-white rounded-xl shadow-sm overflow-x-auto"><table className="w-full min-w-[1050px] text-xs text-left"><thead className="bg-slate-50 text-gray-500"><tr>{['Transaction ID','Property ID','ক্যাটাগরি','ধরণ','পরিমাণ','Payment method','স্ট্যাটাস','তারিখ'].map((heading) => <th key={heading} className="p-4">{heading}</th>)}</tr></thead><tbody>{transactions.map((transaction) => <tr key={transaction.id} className="border-t border-gray-100"><td className="p-4 font-semibold text-gray-900">{transaction.id}</td><td className="p-4 text-gray-600">{transaction.property}</td><td className="p-4 text-gray-700">{transaction.category}</td><td className="p-4"><span className={transaction.type === 'Income' ? 'text-[#00875A] font-bold' : 'text-red-600 font-bold'}>{transaction.type === 'Income' ? 'ইনকাম' : 'খরচ'}</span></td><td className="p-4 font-bold text-gray-900">{money(transaction.amount)}</td><td className="p-4 text-gray-600">{transaction.method}</td><td className="p-4"><span className={`rounded-full px-2 py-1 font-bold ${statusStyle(transaction.status)}`}>{transaction.status}</span></td><td className="p-4 text-gray-500">{transaction.date}</td></tr>)}</tbody></table></div></section>;
}
